// All economy numbers live here. Money is integer rupees. One game "week" = one tick.
export const B = {
  startCash: 500000,
  maxEnergy: 10,
  energyRegen: 2,
  tickMs: 25000,
  maxCatchupTicks: 8,
  baseSlots: 3,
  slotsPerOffice: 2,
  marketPoolMax: 10,
  marketSpawnEvery: 2,
  leadChanceBase: 0.35,
  leadChancePerMarketing: 0.08,
  maxOpenLeads: 12,
  leadLifeWeeks: 5,
  contactEnergy: 1,
  visitEnergy: 2,
  commissionBase: 0.02,
  commissionPerCS: 0.002,
  xpContact: 5,
  xpVisit: 15,
  xpDeal: 50,
  xpPerCommission: 10000,
  maxRounds: 5,
  upgradeMax: 5,
  upgradeGrowth: 1.8,
  boostLeads: 2,
};
